# Generated by Django 3.1 on 2021-02-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('contact_num', models.IntegerField()),
                ('Appointment_date', models.DateField()),
                ('doctor_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointmentapp.doctor')),
            ],
        ),
    ]
